### ISSUE TITLE
[Bug]: Signs request Script Injection permissions.

### ISSUE THREAD

**Issue by RyanLua** [RyanLua/Signs#13]
### Contact Details

https://devforum.roblox.com/u/winnerstakesall

### What happened?

Signs requests for permission to inject scripts but it never does. Disabling the permission has no effect on Signs.

![eaa13dc09fb6c56a8e8d18723c11ee31f872dee9_2_1035x231](https://user-images.githubusercontent.com/80087248/231309093-da008773-284f-4db8-9c4f-72de7918355c.png)

### Steps to reproduce

```shell
1. Open Roblox Studio
2. Go to PLUGINS tab
3. Click Manage Plugins
4. Find that Signs needs Script Injection permissions
```

### Other details

https://devforum.roblox.com/t/what-triggers-the-plugin-script-injection-permission/2289530

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RyanLua** [comment]
Unable to resolve this issue. Can't really find information about how to disable permissions.

**Comment by VSCPlays** [comment]
I noticed something odd, I’m unable to experience this bug, so this is just a visual bug on roblox (doesn’t apply to me though)

![IMG_1073](https://github.com/RyanLua/Signs/assets/133564013/c11a7656-f5e7-4c6f-9beb-a5f8abb975fd)

**Comment by RyanLua** [comment]
> I noticed something odd, I’m unable to experience this bug, so this is just a visual bug on roblox (doesn’t apply to me though)
> 
> ![IMG_1073](https://user-images.githubusercontent.com/133564013/241779541-c11a7656-f5e7-4c6f-9beb-a5f8abb975fd.jpeg)

That's odd since permissions are requested for me even after reinstalling.
![image](https://github.com/RyanLua/Signs/assets/80087248/08d4d173-5b93-4f37-ab88-5e3f108157e2)

**Comment by RyanLua** [comment]
This problem is really hard to properly reproduce and sometimes requests no permission, so I think this is something on Roblox's end or similar.
