### ISSUE TITLE
[Bug]: Preview will clip out of frame if rotated

### ISSUE THREAD

**Issue by RyanLua** [RyanLua/Signs#22]
### Contact Details

https://twitter.com/RaenLua

### What happened?

If you set the background to any color and rotate, it will clip out of the preview frame.

### Steps to reproduce

```shell
1. Open Signs
2. Set the color to white and transparency to 0
3. Set rotation to 45 degrees
4. Look at how it clips out of frame
```

### Other details

![image](https://user-images.githubusercontent.com/80087248/235332820-af2a4699-8f51-4f2c-813a-93e577fe40ec.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VSCPlays** [comment]
A way to fix this issue is to use `CanvasGroup` as it prevents it’s children from clipping out of the `CanvasGroup`

**Comment by RyanLua** [comment]
> A way to fix this issue is to use `CanvasGroup` as it prevents it’s children from clipping out of the `CanvasGroup`

Thanks for the idea. I will try this soon.

**Comment by RyanLua** [comment]
CanvasGroup does not work with ZIndexBehavior set to Sibling for some odd reason.

![image](https://github.com/RyanLua/Signs/assets/80087248/a5491d13-cb52-4c50-9190-086154625063)

I was able to fix the issue, but some bugs and problems could arise from CanvasGroup and its buggy nature. CanvasGroup does have its limitations such as using a lot of memory and such.

![image](https://github.com/RyanLua/Signs/assets/80087248/a35dc1f8-1535-4bfc-8079-a111571c26d9)
